
var arrLang = {
  'en': {
    'polytech':'Polytech',
    "mainMenu": "Main menu",
    "createCustomCharacter": "Create custom character",
    "gameStatistics": "Game statistics",
    "photoAlbum": "Photo album",
    "progressView": "Progress view",
    "dailyContents": "Daily contents",
    "dialogueSystem": "Dialogue system",
    "movement": "Movement",
    "levelSystem": "Level system",
    "settings": "Settings",
    "description1": "Attracting new students to the Polytechnic College, motivating students to approach the learning process more creatively by depicting their daily life in a creative way.",
    "description2": "Computer game \"Polytech\" about my college.",
    "programminglanguagepolytech": "Programming language: C#",
    "developmentenvironmentpolytech": "Development environment: Unity",
    "developmenttimepolytech": "Development time: December 2022 - January 2023",
    "mainmenu": "Main menu (entrance)",
        "gamestart": "Game start",
        "createcharacter": "Create character",
        "gallery": "Gallery of moments",
        "daycontent": "Day's content",
        "gameprogress": "Game progress",
        "settings": "Settings",
    'h1-planets':'Planets of the Solar System',
    'head-planets':'Planets of the Solar System',
    'slide1': 'Home screen',
    'slide2': 'Settings',
    'slide3': 'Warning',
    'slide4': 'Menu',
    'slide5': 'Introduction',
    'slide6': 'Story of other characters',
    'slide7': 'Meeting other characters',
    'slide8': 'Example character description',
    'slide9': 'A few more characters...',
    'slide10': 'Example character description',
    'slide11': 'Flying to menu unlock',
    'slide12': 'Menu with unlocked options',
    'slide13': 'Section about planets. Introduction',
    'slide14': 'Earth planet',
    'slide15': 'Arrange planets in the right order to the Sun',
    'slide16': 'Arrange planets in the right order by size',
    'slide17': 'Create your own planet',
    'slide18': 'Example of created planet',
    'slide19': 'One of the tests',
    'slide20': 'Section about aliens. Introduction',
    'slide21': 'Create your own alien',
    'slide22': 'Example of created alien',
    'slide23': 'Interesting facts about space',
    'slide24': 'Planet races',
    'programmingLanguage': 'Programming language: Delphi 11',
    'developmentEnvironment': 'Development environment: Embarcadero',
    'developmentTime': 'Development time: June 2022',
    'gameContent': 'Game content includes:',
   
    'intro': 'Introduction',
    'menu': 'Menu for navigation',
    'colorfulSections': 'Multiple colorful sections with theory',
    'knowledgeTests': 'Knowledge tests',
    'reptiloidTest': 'Reptiloid test',
    'areYouFromThisPlanet': 'Are you from this planet?',
    'whichPlanetAreYouFrom': 'Which planet are you from?',
    'gamesHeader': 'Games:',
    'spaceRaces': 'Space races',
    'puzzles': 'Puzzles',
    'arrangePlanets': 'Arrange planets in the right order games',
    'createPlanet': 'Create your own planet game',
    'createAlien': 'Create your own alien game',
    'viewHelp': 'View help',
     'educationalAndEntertainmentApp': 'Educational and entertainment app for studying space, planets, and the Solar System.',
    'userEngagementDescription': 'Introducing mass users to Earth group planets, interesting space phenomena, theories in astrobiology, and demonstrating various cosmic events through visualization. The created app is designed for users of all kinds. It can be used not only by people who have previously studied space but also by those who are simply interested in the topic.',
    'choose-lang':'Select the language',
    'resume': 'Resume',
    'name': 'Polina Kuzmenok',
    'location':'Grodno, Belarus',
    'mobile':'Mobile phone',
    'email':'E-mail',
    'age': 'Age',
    'my-age':'18 years old (born 06.08.2005)',
    'education':'Education',
    'my-education':'GSPC, Grodno (Grodno State Polytechnic College)',
    'qualification':'Qualification: Programmer technician',
    'specialization':'Specialization: "Software for processing economic and business information"',
    'time-of-education':'Term of study: 2020 – present time (release in June 2024)',
    'experience':'Experience',
    'sqilsoft-term':'Feb. - Mar. 2023',
    'sqilsoft':'Grodno IT company (production practice in the 3rd year)',
    'linux':'Learning and working with Linux OS',
    'docker':'Learning Docker technology',
    'jira':'Working with Jira, BitBucket, Confluence',
    'timer-prod':'Development of Your Timer application',
    'hobby':'Hobbies',
    'dance':'Dancing',
    'bicycle':'Bicucling',
    'paint':'Painting',
    'cook':'Cooking',
    'chess':'Chess',
    'read':'Reading',
    'interests':'Interests',
    'history':'History',
    'cryptozoo':'Cryptozoology',
    'detective':'Detectives',
    'criminalistics':'Criminalistics',
    'human-rights':'Justice and law',
    'leisure':'Leisure',
    'makeup': 'Makeup',
    'social-media':'I\'m on social media',

    'aside-content':'Content',
    'cont':'Content',
    'aside-education':'Education',
    'aside-experience':'Experience',
    'aside-projects':'Projects',
    'aside-skills':'Skills',
    'aside-languages':'Languages',
    'aside-hobbies':'Leisure',
    'languages':'Languages',
    'rus-lang':'Русский язык / Russian (native, primary)',
    'bel-lang':'Беларуская мова / Belorussian (native, non-primary)',
    'eng-lang':'English (Upper-Intermediate)',
    'spa-lang':'Español / Spanish (basic knowledge)',
    'skills':'Skills',
    'web':'Web development:',
    'pro-lang':'Programming languages:',
    'base':'Basic knowledge:',
    '1c':'1C Accounting',
    'approach':'Approach to work:',
    'thinking':'Out-of-the-box thinking and creativity',
    'quality':'Work on quality and integrity',
    'learn':'Learnability:',
    'fast-learn':'Fast learning ability and desire to develop',
    "critic":'Receptivity to constructive criticism',
    'personality':'Personality:',
    'friend':'Friendliness',
    'sociability':'Sociability',
    'versitility':'Versatility',
    'organization':'Organization of work: ',
    'multitask':'Multitasking',
    'time-manage':'Time management',
    'design_':'Design:',
    'web-design':'Web Design, Graphic Design, UI/UX',
    'program-own':'Program ownership:',
    'os':'Operating systems:',
    'windows':'Windows (main)',
    'lin':'Linux (have experience)',
    'proj':'Projects',
    'proj-timer':'Timer application on the Angular framework',
    'proj-timer-repo':'Repository on GitHub',
    'proj-timer-while':'It was created during practice in the 3rd year',
    'proj-timer-website':'"Your Timer" website',
    'proj-tree':'An application for creating and visualizing a family tree',
    'proj-tree-repo':'Repository on GitHub',
    'proj-tree-while':'It was created as a course project at the end of the 3rd year',
    'proj-tree-app':'View the app',
    'proj-planets':'A gaming and educational application for exploring the planets of the Solar System',
    'proj-planets-name':'Planets of the Solar System',
    'proj-planets-while':'It was created as a course project at the end of the 2nd year',
    'proj-planets-repo':'Repository on GitHub',
    'proj-planets-app':'View the app',
    'proj-polytech':'A game about polytech (my college)',
    'proj-polytech-repo':'Repository on GitHub',
    'proj-polytech-while':'A project for an academic discipline in the 3rd year',
    'proj-polytech-name':'Polytech',
    'proj-polytech-app':'View the app',
    'proj-proflex':'Frontend part of the website for studying the discipline "Professional vocabulary (English)"',
    'proj-proflex-repo':'Repository on GitHub',
    'proj-proflex-while':'It was created during practice in the 2nd year',
    'proj-proflex-website':'"Proflex" website',
    'small-sites':'...as well as small sites for practice in web development.',
    'dark-mode':'Dark mode',
    'description':'Description',
    'proj-descr':'Project description',
    'text-descr-tree':'A computer application for creating and editing family trees.',
    'goal':'Project objective',
    'goal-tree':'Develop software that provides a user-friendly and intuitive interface that will allow users to easily create, edit and visualize their family trees. The software product provides a convenient and visual representation of genealogical information, allowing users to revive their genealogical history and view their family ties electronically.',
    'repo':'Repository link',
    'docs':'Documentation',
    'links': 'Links',

    'techno':'Technologies',
    'language-tree':'Programming language: C#',
    'environment-tree':'Development environment: Microsoft Visual Studio',
    'framework-tree':'Framework: Windows Presentation Foundation (WPF)',
    'libs-tree':'Libraries: GiGraph (based on Graphviz)',
    'develop':'Development',
    'develop-tree-time':'Development time: June 2023',
    'stages':'Stages of development:',
    'problem':'Problem statement',
    'design':'Designing',
    'realize':'Realization',
    'test':'TestingTesting',
    'app':'Application',
    'menu': 'Menu',
    'menuDescription': 'Four main menu items that allow the user to navigate through the necessary tables and modify them:',
    'persons': 'Persons - with this item, you can make changes to the persons table in the database',
    'places': 'Places - with this item, you can make changes to the places table in the database',
    'events': 'Events - with this item, you can make changes to the events table in the database',
    'tree': 'Tree - with this item, you can create a genealogical tree based on data from the table',
    'settings': 'And settings:',
    'openCreateDB': 'Open/create new database',
    'openExamplesDB': 'Open examples of ready-made databases',
    'openHelp': 'Open help',
    'functions': 'Functions',
    'basicFunctions': 'Four main functions with all tables:',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'additionalFunctions': 'Additional functions in "Persons":',
    'filter': 'Filter',
    'sort': 'Sort',

    'view': 'View',
    'mainMenu': 'Main menu',
    'personsTable': 'Persons table',
    'placesTable': 'Places table',
    'eventsTable': 'Events table',
    'addPerson': 'Add person',
    'editPerson': 'Edit person',
    'viewPerson': 'View person',
    'addEditPlace': 'Add/edit place',
    'viewPlaces': 'View places',
    'addEditEvent': 'Add/edit event',
    'viewEvent': 'View event',
    'createTree': 'Create tree',
    'selectTreeSettings': 'Select tree settings',
    'createdGenealogicalTree': 'Created genealogical tree',
    'filterNoPhoto': 'Filter (showing only people without photos)',
    'filterAlive': 'Filter (showing only living people)',
    'other': 'Other',
    'contents': 'Content',
    'description': 'Description',
    'technologies': 'Technologies',
    'development': 'Development',
    'view': 'View',
    'home': '> Home'



  },



  'ru': {
    'polytech':'Политех',

    "mainMenu": "Главное меню",
    "createCustomCharacter": "Создание кастомного персонажа",
    "gameStatistics": "Игровая статистика",
    "photoAlbum": "Фотоальбом",
    "progressView": "Просмотр прогресса",
    "dailyContents": "Содержание дней",
    "dialogueSystem": "Диалоговая система",
    "movement": "Передвижение",
    "levelSystem": "Уровневая система",
    "settings": "Настройки",
    "description1": "Привлечение новых учащихся в Политехнический колледж, мотивирование студентов к более творческому подходу к учебному процессу, отображение их повседневной жизни в креативной форме.",
    "description2": "Компьютерная игра «Политех» о моем колледже.",
    "programminglanguagepolytech": "Язык программирования: C#",
    "developmentenvironmentpolytech": "Среда разработки: Unity",
    "developmenttimepolytech": "Время разработки: декабрь 2022 — январь 2023",
    "mainmenu": "Главное меню (вход)",
    "gamestart": "Начало игры",
    "createcharacter": "Создание персонажа",
    "gallery": "Галерея моментов",
    "daycontent": "Содержание дней",
    "gameprogress": "Игровой прогресс",
    "settings": "Настройки",
    'slide1': 'Начальный экран',
    'slide2': 'Настройки',
    'slide3': 'Предупреждение',
    'slide4': 'Меню',
    'slide5': 'Часть знакомства',
    'slide6': 'Рассказ о других персонажах',
    'slide7': 'Знакомство с другими персонажами',
    'slide8': 'Пример описания персонажа',
    'slide9': 'Ещё немного персонажей...',
    'slide10': 'Пример описания персонажа',
    'slide11': 'Летим к разблокировке меню',
    'slide12': 'Меню с разблокированными опциями',
    'slide13': 'Раздел о планетах. Введение',
    'slide14': 'Земля',
    'slide15': 'Расставь планеты в правильном порядке до Солнца',
    'slide16': 'Расставь планеты в правильном порядке по возрастанию',
    'slide17': 'Создай свою планету',
    'slide18': 'Пример созданной планеты',
    'slide19': 'Один из тестов',
    'slide20': 'Раздел об инопланетянах. Введение',
    'slide21': 'Создай своего инопланетянина',
    'slide22': 'Пример созданного инопланетянина',
    'slide23': 'Интересные факты о космосе',
    'slide24': 'Гонки планет',
    'gameContent': 'Игра включает в себя:',
    'intro': 'Знакомство',
    'menu': 'Меню для перехода по разделам',
    'colorfulSections': 'Множество красочных разделов с теорией',
    'knowledgeTests': 'Тесты для закрепления знаний',
    'reptiloidTest': 'Тест на рептилоида',
    'areYouFromThisPlanet': 'А ты точно с этой планеты?',
    'whichPlanetAreYouFrom': 'С какой ты планеты?',
    'gamesHeader': 'Игры:',
    'spaceRaces': 'Игра «Космические гонки»',
    'puzzles': 'Игра «Паззлы»',
    'arrangePlanets': 'Игры «Расставь планеты в правильном порядке»',
    'createPlanet': 'Игра «Создай свою планету»',
    'createAlien': 'Игра «Создай своего пришельца»',
    'viewHelp': 'Просмотр справки',
    'programmingLanguage': 'Язык программирования: Delphi 11',
    'developmentEnvironment': 'Среда разработки: Embarcadero',
    'developmentTime': 'Время разработки: июнь 2022',
    'educationalAndEntertainmentApp': 'Познавательное и развлекательное приложение для изучения космоса, планет и Солнечной системы.',
    'userEngagementDescription': 'Знакомство массовых пользователей с планетами группы Земля, интересными явлениями в космосе, теориями в астробиологии и демонстрацией различных космических событий с помощью визуализации. Созданное приложение рассчитано на пользователей всех видов. Оно может быть использовано не только людьми, которые ранее изучали космос, но и теми, кто просто интересуется этой темой.',
    'choose-lang':'Выберите язык',
    'resume':'Резюме',
    'name':'Полина Кузьменок',
    'location':'Гродно, Беларусь',
    'mobile':'Мобильный телефон',
    'email':'Электронная почта',
    'age': 'Возраст',
    'my-age':'18 лет (род. 06.08.2005)',
    'education':'Образование',
    'my-education':'ГГПК, Гродно (Гродненский государственный политехнический колледж)',
    'qualification':'Квалификация: техник-программист',
    'specialization':'Специализация: «Программное обеспечение обработки экономической и деловой информации»',
    'time-of-education':'Срок обучения: 2020 – наст. время (выпуск в июне 2024)',
    'experience':'Опыт',
    'sqilsoft-term':'фев. - март 2023',
    'sqilsoft':'Гродненская IT-компания (производственная практика на 3 курсе)',
    'linux':'Изучение и работа с ОС Linux',
    'docker':'Изучение технологии Docker',
    'jira':'Работа с Jira, BitBucket, Confluence',
    'timer-prod':'Разработка приложения Your Timer',
    'hobby':'Хобби',
    'dance':'Танцы',
    'bicycle':'Велосипед',
    'paint':'Рисование',
    'cook':'Кулинария',
    'chess':'Шахматы',
    'read':'Чтение',
    'interests':'Интересы',
    'makeup':'Визаж',
    'history':'История',
    'cryptozoo':'Криптозоология',
    'detective':'Детективы',
    'criminalistics':'Криминалистика',
    'human-rights':'Право',
    'leisure':'Увлечения',
    'social-media':'Я в социальных сетях',
    'aside-content':'Содержание',
    'cont':'Содержание',
    'aside-education':'Образование',
    'aside-experience':'Опыт',
    'aside-projects':'Проекты',
    'aside-skills':'Навыки',
    'aside-languages':'Языки',
    'aside-hobbies':'Увлечения',
    'languages':'Языки',
    'rus-lang':'Русский язык (родной, основной)',
    'bel-lang':'Беларуская мова / Белорусский язык  (родной, не основной)',
    'eng-lang':'English / Английский язык (Upper-Intermediate)',
    'spa-lang':'Español / Испанский язык (базовые знания)',
    'web':'Веб-разработка:',
    'pro-lang':'Языки программирования:',
    'base':'Основы в рамках учебной программы:',
    '1c':'1C Бухгалтерия',
    'skills':'Навыки',
    'approach':'Подход к работе:',
    'thinking':'Нестандартное мышление и креативность',
    'quality':'Работа на качество и добросовестность',
    'learn':'Обучаемость',
    'fast-learn':'Быстрая обучаемость и желание развиваться',
    "critic":'Восприимчивость к конструктивной критике',
    'personality':'Характер',
    'friend':'Дружелюбие',
    'sociability':'Общительность',
    'versitility':'Разносторонность',
    'organization':'Организация работы',
    'multitask':'Мультизадачность',
    'time-manage':'Тайм-менеджмент',
    'design_':'Дизайн:',
    'web-design':'Веб-дизайн, графический дизайн, UI/UX',
    'program-own':'Владение программами:',
    'os':'Операционные системы:',
    'windows':'Windows (основная)',
    'lin':'Linux (есть опыт)',
    'proj':'Проекты',
    'proj-timer':'Приложение таймера на фреймворке Angular',
    'proj-timer-repo':'Репозиторий на GitHub',
    'proj-timer-while':'Создавался во время практики на 3 курсе',
    'proj-timer-website':'Сайт «Your Timer»',
    'proj-tree':'Приложение для создания и визуализации генеалогического древа',
    'proj-tree-repo':'Репозиторий на GitHub',
    'proj-tree-while':'Создавался в качестве курсового проекта в конце 3 курса',
    'proj-tree-app':'Просмотреть приложение',
    'proj-planets':'Игровое и познавательное приложение для знакомства с планетами Солнечной системы',
    'proj-planets-name':'Планеты Солнечной системы ',
    'proj-planets-repo':'Репозиторий на GitHub',
    'proj-planets-while':'Создавался в качестве курсового проекта в конце 2 курса',
    'proj-planets-app':'Просмотреть приложение',
    'proj-polytech':'Игра про политех (мой проект для учебной дисциплины на 3 курсе)',
    'proj-polytech-repo':'Репозиторий на GitHub',
    'proj-polytech-name':'Политех',
    
    'proj-polytech-app':'Просмотреть приложение',
    'proj-polytech-while':'Проект для учебной дисциплины на 3 курсе',
    'proj-proflex':'Фронтенд часть сайта для изучения дисциплины «Профессиональная лексика (английский язык)»',
    'proj-proflex-repo':'Репозиторий на GitHub',
    'proj-proflex-website':'Сайт «Proflex»',
    'proj-proflex-while':'Создавался во время практики на 2 курсе',

    'small-sites':'...а также небольшие сайты для практики в веб-разработке.',
    'dark-mode':'Тёмный режим',

        'description':'Описание',
    'proj-descr':'Описание проекта',
    'text-descr-tree':'Компьютерное приложение для создания и редактирования генеалогических деревьев.',
    'goal':'Цель проекта',
    'goal-tree':'Разработать программное обеспечение, обеспечивающее удобный и интуитивно понятный интерфейс, который позволит пользователям легко создавать, редактировать и визуализировать свои генеалогические древа. Программный продукт обеспечивает удобное и наглядное представление генеалогической информации, позволяя пользователям оживить свою генеалогическую историю и просматривать в электронном виде свои родственные связи.',
    'links':'Ссылки',

    'repo':'Репозиторий',
    'docs':'Документация',
    'techno':'Технологии',
    'language-tree':'Язык программирования: C#',
    'environment-tree':'Среда разработки: Microsoft Visual Studio',
    'framework-tree':'Фреймворк: Windows Presentation Foundation (WPF)',
    'libs-tree':'Библиотеки: Cigraph (на основе Graphviz)',
    'develop':'Разработка',
    'develop-tree-time':'Время разработки: июнь 2023',
    'stages':'Этапы разработки:',
    'problem':'Постановка задачи',
    'design':'Проектирование',
    'realize':'Реализация',
    'test':'Тестирование',
    'app':'Применение',
    'menu': 'Меню',
    'menuDescription': 'Четыре основных пункта меню, при помощи которых пользователь может перемещаться по нужным таблицам и изменять их:',
    'persons': 'Персоны - с помощью этого пункта можно вносить изменения в таблицу персон базы данных',
    'places': 'Места - с помощью этого пункта можно вносить изменения в таблицу мест базы данных',
    'events': 'События - с помощью этого пункта можно вносить изменения в таблицу событий базы данных',
    'tree': 'Древо - с помощью этого пункта можно создавать генеалогическое древо на основе данных таблицы',
    'settings': 'А также пункт меню «Настройки», позволяющий:',
    'openCreateDB': 'Открыть/cоздать новую базу',
    'openExamplesDB': 'Открыть примеры готовых баз данных',
    'openHelp': 'Открыть справку',
    'functions': 'Функции',
    'basicFunctions': 'Четыре основные функции со всеми таблицами:',
    'add': 'Добавление',
    'edit': 'Изменение',
    'delete': 'Удаление',
    'view': 'Просмотр',
    'additionalFunctions': 'Дополнительные функции в «Персонах»:',
    'filter': 'Фильтрация',
    'sort': 'Сортировка',
    'view': 'Просмотр',
    'mainMenu': 'Главное меню',
    'personsTable': 'Таблица персон',
    'placesTable': 'Таблица мест',
    'eventsTable': 'Таблица событий',
    'addPerson': 'Добавление персоны',
    'editPerson': 'Изменение персоны',
    'viewPerson': 'Просмотр персоны',
    'addEditPlace': 'Добавление/изменение места',
    'viewPlaces': 'Просмотр мест',
    'addEditEvent': 'Добавление/изменение события',
    'viewEvent': 'Просмотр события',
    'createTree': 'Создание древа',
    'selectTreeSettings': 'Выбор других настроек древа',
    'createdGenealogicalTree': 'Созданное генеалогическое древо',
    'filterNoPhoto': 'Фильтрация (показаны только люди без фото)',
    'filterAlive': 'Фильтрация (показаны только живые люди)',
    'other': 'Прочее',
    'contents': 'Содержание',
    'description': 'Описание',
    'technologies': 'Технологии',
    'development': 'Разработка',
    'view': 'Просмотр',
    'home': '> На главную'

  },


  





  
   'be': {
    'polytech':'Полiтэх',

    "mainMenu": "Галоўнае меню",
    "createCustomCharacter": "Стварэнне кастамнага персанажа",
    "gameStatistics": "Гульнявая статыстыка",
    "photoAlbum": "Фотаальбом",
    "progressView": "Прагляд прагрэсу",
    "dailyContents": "Змест дзён",
    "dialogueSystem": "Дыялогавая сістэма",
    "movement": "Рух",
    "levelSystem": "Сістэма ўзроўню",
    "settings": "Настройкі",
    "description1": "Прыцягненне новых студэнтаў у Палітэхнічны каледж, мацывацыя студэнтаў падыходзіць да навучальнага працэсу болей творча, адлюстроўванне іх павседневай жыцця ў творчай форме.",
    "description2": "Кампутарная гульня «Палітэх» аб маім каледжы.",
    "programminglanguagepolytech": "Мова праграмавання: C#",
    "developmentenvironmentpolytech": "Сярэдовішча распрацоўкі: Unity",
    "developmenttimepolytech": "Час распрацоўкі: снежань 2022 — студзень 2023 г.",
    "mainmenu": "Галоўнае меню (уваход)",
    "gamestart": "Пачатак гульні",
    "createcharacter": "Стварыць персанажа",
    "gallery": "Галерэя момантаў",
    "daycontent": "Змест дня",
    "gameprogress": "Ход гульні",
    "settings": "Налады",
    'head-planets':'Планеты Сонечнай сiстэмы',
    'h1-planets':'Планеты Сонечнай сiстэмы',
    'slide1': 'Стартавы экран',
    'slide2': 'Настройкі',
    'slide3': 'Папярэджанне',
    'slide4': 'Меню',
    'slide5': 'Вводны',
    'slide6': 'Расказ пра іншых персанажаў',
    'slide7': 'Знаёмство з іншымі персанажамі',
    'slide8': 'Прыклад апісання персанажа',
    'slide9': 'Яшчэ некалькі персанажаў...',
    'slide10': 'Прыклад апісання персанажа',
    'slide11': 'Палёт да разблакіравання меню',
    'slide12': 'Меню з разблакаванымі опцыямі',
    'slide13': 'Раздзел аб планетах. Увод',
    'slide14': 'Зямля',
    'slide15': 'Размясціце планеты ў правільным парадку да Сонца',
    'slide16': 'Размясціце планеты ў ўзрастанні',
    'slide17': 'Стварыце сваю ўласную планету',
    'slide18': 'Прыклад створанай планеты',
    'slide19': 'Адзін з тэставаў',
    'slide20': 'Раздзел аб іншаземцы. Увод',
    'slide21': 'Стварыце свайго іншаземца',
    'slide22': 'Прыклад створанага іншаземца',
    'slide23': 'Цікавыя факты пра космас',
    'slide24': 'Гонкі планет',
    'programmingLanguage': 'Мова праграмавання: Delphi 11',
    'developmentEnvironment': 'Асяроддзе распрацоўкі: Embarcadero',
    'developmentTime': 'Час распрацоўкі: чэрвень 2022',
    'gameContent': 'Гульня ўключае ў сябе:',
    'intro': 'Знаёмства',
        'menu': 'Меню для пераходу па раздзелы',
        'colorfulSections': 'Шмат барвістых раздзелаў з тэорыяй',
        'knowledgeTests': 'Тэсты для ўцяварэння ведаў',
        'reptiloidTest': 'Тэст на рэптылоіда',
        'areYouFromThisPlanet': 'Ці ты ўпэўнены ў тым, што ты з гэтай планеты?',
        'whichPlanetAreYouFrom': 'З якой ты планеты?',
        'gamesHeader': 'Гульні:',
        'spaceRaces': 'Гульня «Касмічныя гонкі»',
        'puzzles': 'Гульня «Галаваломкі»',
        'arrangePlanets': 'Гульні «Размясціце планеты ў правільным парадку»',
        'createPlanet': 'Гульня «Ствары сваю ўласную планету»',
        'createAlien': 'Гульня «Ствары свайго іншапланетца»',
        'viewHelp': 'Прагляд даведкі',
    'educationalAndEntertainmentApp': 'Адукацыйнае і разважлівае прыкладанне для вучэння космасу, планет і Сонечнай сістэмы.',
    'userEngagementDescription': 'Знаёмства масавых карыстальнікаў з плянетамі групы Зямля, цікавымі явішчамі ў космасе, тэорыямі ў астрабіялогіі і дэманстрацыяй розных космічных падзей з дапамогай візуалізацыі. Створанае прыкладанне прызначана для карыстальнікаў усіх відаў. Яго можна выкарыстоўваць не толькі тымі, хто раней вучыў космас, але і тымі, хто проста цікавіцца гэтай тэмай.',
    'choose-lang':'Выберыце мову',

    'name':'Палiна Кузьмянок',
    'resume':'Рэзюмэ',
    'location':'Гродна, Беларусь',
    'mobile':'Мабільны тэлефон',
    'email':'Электронная пошта',
    'age': 'Узрост',
    'my-age':'18 гадоў (нар. 06.08.2005)',
    'education':'Адукацыя',
    'my-education':'ГДПК, Гродна (Гродзенскі дзяржаўны політэхнічны каледж)',
    'qualification':'Кваліфікацыя: тэхнік-праграміст',
    'specialization':'Спецыялізацыя: «Праграмнае забеспячэнне апрацоўкі эканамічнай і дзелавой інфармацыі»',
    'time-of-education':'Тэрмін навучання: 2020- сапр. час (выпуск у чэрвені 2024)',
    'experience':'Вопыт',
    'sqilsoft-term':'люты - сак. 2023',
    'sqilsoft':'Гродзенская IT-кампанія (вытворчая практыка на 3 курсе)',
    'linux':'Вывучэнне і праца з АС Linux',
    'docker':'Вывучэнне тэхналогіі Docke',
    'jira':'Праца з Jira, BitBucket, Confluence',
    'timer-prod':'Распрацоўка прыкладання Your Timer',

    'hobby':'Хобi',
    'dance':'Танцы',
    'bicycle':'Веласпорт',
    'paint':'Маляванне',
    'cook':'Кулiнарыя',
    'chess':'Шахматы',
    'read':'Чытанне',
    'interests':'Iнтарэсы',
    'history':'Гiсторыя',
    'cryptozoo':'Крыптазаалогiя',
    'detective':'Дэтэктывы',
    'makeup':'Візаж',
    'criminalistics':'Крымiналiстыка',
    'human-rights':'Закон і права',
    'leisure':'Заняткi',
    'social-media':'Я ў сацыяльных сетках',

    'aside-content':'Змест',
    'cont':'Змест',
    'aside-education':'Адукацыя',
    'aside-experience':'Вопыт',
    'aside-projects':'Праекты',
    'aside-skills':'Навыкi',
    'aside-languages':'Мовы',
    'aside-hobbies':'Заняткi',
    'languages':'Мовы',
    'rus-lang':'Русский язык / Руская мова (родная, асноўная)',
    'bel-lang':'Беларуская мова (родная, не асноўная)',
    'eng-lang':'English / Англiйская мова (Upper-Intermediate)',
    'spa-lang':'Español / Iспанская мова (базавыя веды)',
    'web':'Вэб-распрацоўка:',
    'pro-lang':'Мовы праграмавання:',
    'base':'Асновы ў рамках вучэбнай праграмы:',
    '1c':'1C Бухгалтэрыя',
    'skills':'Навыкi',
    'approach':'Падыход да працы:',
    'thinking':'Нестандартнае мысленне і крэатыўнасць',
    'quality':'Праца на якасць і добрасумленнасць',
    'learn':'Навучальнасць:',
    'fast-learn':'Хуткая навучальнасць і жаданне развівацца',
    "critic":'Успрымальнасць да канструктыўнай крытыцы',
    'personality':'Характар:',
    'friend':'Прыязнасць',
    'sociability':'Таварыскасць',
    'versitility':'Рознабаковасць',
    'organization':'Арганізацыя працы:',
    'multitask':'Мультызадачнасць',
    'time-manage':'Самаарганізацыя',

    'design_':'Дызайн:',
    'web-design':'Вэб-дызайн, графiчны дызайн, UI/UX',
    'program-own':'Валоданне праграмамi:',
    'os':'Аперацыйныя сiстэмы:',
    'windows':'Windows (асноўная)',
    'lin':'Linux (ёсць вопыт)',
    'proj':'Праекты',
    'proj-timer':'Дадатак таймера на фрэймворке Angular',
    'proj-timer-repo':'Сайт «Your Timer»',
    'proj-timer-while':'Ствараўся падчас практыкі на 3 курсе',
    'proj-timer-website':'Рэпазітар на GitHub',
    'proj-tree':'Прыкладанне для стварэння і візуалізацыі генеалагічнага дрэва',
    'proj-tree-repo':'Рэпазітар на GitHub',
    'proj-tree-while':'Ствараўся ў якасці курсавога праекта ў канцы 3 курса',
    'proj-tree-app':'Прагледзець дадатак',
    'proj-planets':'Гульнявое і пазнавальнае прыкладанне для знаёмства з планетамі Сонечнай сістэмы',
    'proj-planets-name':'Планеты Сонечнай сістэмы',
    'proj-planets-while':'Ствараўся ў якасці курсавога праекта ў канцы 2 курса',
    'proj-planets-repo':'Рэпазітар на GitHub',
    'proj-planets-app':'Прагледзець дадатак',
    'proj-polytech':'Гульня пра палітэх (мая навучальная ўстанова)',
    'proj-polytech-repo':'Рэпазітар на GitHub',
    'proj-polytech-name':'Політэх',
    'proj-polytech-app':'Прагледзець дадатак',
    'proj-polytech-while':'Праект для вучэбнай дысцыпліны на 3 курсе',

    'proj-proflex':'Фронтэнд частка сайта для вывучэння дысцыпліны «Прафесійная лексіка (англійская мова)»',
    'proj-proflex-repo':'Рэпазітар на GitHub',
    'proj-proflex-website':'Сайт «Proflex»',
    'proj-proflex-while':'Ствараўся падчас практыкі на 2 курсе',

    'small-sites':'...а таксама невялікія сайты для практыкі ў вэб-распрацоўцы.',
    'dark-mode':'Цёмны рэжым',


    
    'description':'Апісанне',
    'proj-descr':'Апісанне праекта',
    'text-descr-tree':'Камп\'ютэрнае прыкладанне для стварэння і рэдагавання генеалагічных дрэў.',
    'goal':'Мэта праекта',
    'goal-tree':'Распрацаваць праграмнае забеспячэнне, якое забяспечвае зручны і інтуітыўна зразумелы інтэрфейс, які дазволіць карыстальнікам лёгка ствараць, рэдагаваць і візуалізаваць свае генеалагічныя дрэва. Праграмны прадукт забяспечвае зручнае і нагляднае ўяўленне генеалагічнай інфармацыі, дазваляючы карыстальнікам ажывіць сваю генеалагічную гісторыю і праглядаць у электронным выглядзе свае роднасныя сувязі.',
    'links':'Спасылкi',

    'repo':'Рэпазітар',
    'docs':'Дакументацыя',
    'techno':'Тэхналогіi',
    'language-tree':'Мова праграмавання: C#',
    'environment-tree':'Асяроддзе распрацоўкі: Microsoft Visual Studio',
    'framework-tree':'Фрэймворк: Windows Presentation Foundation (WPF)',
    'libs-tree':'Бібліятэкі: GiGraph (на аснове Graphviz)',
    'develop':'Распрацоўка',
    'develop-tree-time':'Час распрацоўкі: чэрвень 2023',
    'stages':'Этапы распрацоўкі:',
    'problem':'Пастаноўка задачы',
    'design':'Праектаванне',
    'realize':'Рэалізацыя',
    'test':'Тэставанне',
    'app':'Прымяненне'
,
'menu': 'Меню',
'menuDescription': 'Чатыры асноўныя пункты меню, з дапамогай якіх карыстальнік можа перамяшчацца па неабходных табліцах і мадыфікаваць іх:',
'persons': 'Асобы - з дапамогай гэтага пункта вы можаце вносіць змены ў табліцу асоб базы даных',
'places': 'Месцы - з дапамогай гэтага пункта вы можаце вносіць змены ў табліцу месцаў базы даных',
'events': 'Падзеі - з дапамогай гэтага пункта вы можаце вносіць змены ў табліцу падзей базы даных',
'tree': 'Дрэва - з дапамогай гэтага пункта вы можаце ствараць генеалагічнае дрэва на аснове дадзеных табліцы',
'settings': 'I налады, якiя дазваляюць: ',
'openCreateDB': 'Адкрыць/стварыць новую базу',
'openExamplesDB': 'Адкрыць прыклады шатовых баз дадзеных',
'openHelp': 'Адкрыць даведку',
    'functions': 'Функцыі',
    'basicFunctions': 'Чатыры асноўныя функцыі з усімі табліцамі:',
    'add': 'Дадаць',
    'edit': 'Рэдагаванне',
    'delete': 'Выдаленне',
    'view': 'Прагляд',
    'additionalFunctions': 'Дадатковыя функцыі ў «Асобах»:',
    'filter': 'Фільтрацыя',
    'sort': 'Сартаванне',
    'view': 'Прагляд',
    'mainMenu': 'Галоўнае меню',
    'personsTable': 'Табліца асоб',
    'placesTable': 'Табліца месцаў',
    'eventsTable': 'Табліца падзей',
    'addPerson': 'Дадаванне асобы',
    'editPerson': 'Рэдагаванне асобы',
    'viewPerson': 'Прагляд асобы',
    'addEditPlace': 'Дадаванне/рэдагаванне месца',
    'viewPlaces': 'Прагляд месцаў',
    'addEditEvent': 'Дадаванне/рэдагаванне падзеі',
    'viewEvent': 'Прагляд падзеі',
    'createTree': 'Стварэнне дрэва',
    'selectTreeSettings': 'Выбар іншых налад дрэва',
    'createdGenealogicalTree': 'Створанае генеалагічнае дрэва',
    'filterNoPhoto': 'Фільтрацыя (паказаныя толькі людзі без фота)',
    'filterAlive': 'Фільтрацыя (паказаныя толькі жывыя людзі)',
    'other': 'Іншае',
    'contents': 'Змест',
    'description': 'Апісанне',
    'technologies': 'Тэхналогіі',
    'development': 'Разработка',
    'view': 'Прагляд',
    'home': '> На галоўную'

   }






   
}

setLang()






function setLang(){


    var lang = localStorage.getItem('language') 


    if(lang=='ru' || lang == 'be' || lang=='en')
{
    $('.translate').each(function(index, item) {
      $(this).removeClass('active')

    });
    $('#'+localStorage.getItem('language')).addClass('active')
    



    $('.lang').each(function(index, item) {
        $(this).text(arrLang[lang][$(this).attr('key')]);
    });
    $('#lang-panel').css('width',$('aside').css('width'))


}}


  $(function() {
    $('.translate').click(function() {

      var lang = $(this).attr('id');


      $('.translate').each(function(index, item) {
        $(this).removeClass('active')

      });
      $(this).addClass('active')
      
  
  

      $('.lang').each(function(index, item) {
        $(this).text(arrLang[lang][$(this).attr('key')]);
      });
      $('#lang-panel').css('width',$('aside').css('width'))
      localStorage.setItem('language', $(this).attr('id'))

    });
  });